apiVersion: v1
kind: Template
metadata:
  name: sonarqube
  labels:
    app: sonarqube
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: sonarqube
      labels:
        app: sonarqube
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: sonarqube
      labels:
        app: sonarqube
    spec:
      source:
        git:
          uri: https://github.com/King-Of-The-Cookies/deploy_sonarqube.git
      output:
        to:
          kind: ImageStreamTag
          name: sonarqube:1
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
