kind: Template
apiVersion: v1
metadata:
  name: sonarqube
  labels:
    app: sonarqube
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: sonarqube
    labels:
      app: sonarqube
  spec:
    replicas: 1

    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: sonarqube
      spec:
        containers:
          - image: 172.30.1.1:5000/sonarcube/sonarqube:1
            name: sonarqube
            ports:
              - containerPort: 9000
                protocol: TCP
            volumeMounts:
              - mountPath: /opt/sonarqube/data
                name: sonarqube-data
        volumes:
          - name: sonarqube-data
            persistentVolumeClaim:
              claimName: "sonarqube-data"
